version: 2

sources:
  - name: oppgaver
    project: oppdrift-369209
    dataset: oppgaver
    tables:
      - name: reisetider
      - name: strekninger_renset
      - name: trafikkregistreringspunkt
      - name: timetrafikk